### PR TITLE
Added UMD

### PR DESCRIPTION
**Pull request by marverix**

### CODE REVIEW

**Review by silkimen — APPROVED** [review]

**Comment by atstp** [comment]
This looks good.

Can you update the patch so that it doesn't re-indent the entire file?

I'll merge it right after!

**Comment by marverix** [comment]
@silkimen @atstp Done :)

**Comment by rmja** [comment]
Could this be merged?

**Comment by themacboy** [comment]
@silkimen

**Comment by themacboy** [comment]
> Could this be merged?

@silkimen

**Comment by silkimen** [comment]
> > Could this be merged?
> 
> 
> 
> @silkimen 

This needs to be merged by a contributor, i.e. @atstp

**Comment by marverix** [comment]
5 years after creating a PR :smiling_face_with_tear:

**Comment by marverix** [comment]
I'm closing this PR, as author clearly doesn't care.

**Pull request closed without merging**
